# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- azure-pipelines

pool:
  vmImage: ubuntu-latest

steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet publish'
  inputs:
    command: publish
    projects: WhatIfDemo-Functions
    publishWebProjects: false
    zipAfterPublish: false
    modifyOutputPath: false

- task: az-func-as-a-graph@1
  inputs:
    projectFolder: '$(System.DefaultWorkingDirectory)'
    outputFile: '$(Build.ArtifactStagingDirectory)/$(Build.Repository.Name).diagram.htm'
    repoUri: '$(Build.Repository.Uri)'
    repoName: '$(Build.Repository.Name)'
    branchName: '$(Build.SourceBranchName)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
