
on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - uses: scale-tone/az-func-as-a-graph@github-action-alpha14
      with:
        projectFolder: WhatIfDemo-Functions
        outputFile: graph.htm

    - uses: actions/upload-artifact@v3
      with:
        path: graph.htm
